mode = "dark"

accent               = "#C9D487"
selection            = "#6C5EB5"
muted                = "#9C94E0"
background           = "#2A2178"
dark_background      = "#221A63"
darker_background    = "#1A1450"
lighter_background   = "#352879"
foreground           = "#C4BFF6"
dark_foreground      = "#9C94E0"
light_foreground     = "#DAD6FA"
bright_foreground    = "#FFFFFF"
red                  = "#E8948A"
yellow               = "#DDE69A"
orange               = "#E0A878"
green                = "#9AE29B"
cyan                 = "#8FE3EA"
blue                 = "#B0B2FF"
magenta              = "#E0A2E3"
brown                = "#8A6A30"
bright_red           = "#F4B0A8"
bright_yellow        = "#EEF3B8"
bright_green         = "#BDF0BE"
bright_cyan          = "#B8F0F4"
bright_blue          = "#CFD0FF"
bright_magenta       = "#EEC4F0"
selection_background = "#6C5EB5"
selection_foreground = "#FFFFFF"
